name: feexpert
recipe: drupal9
config:
  webroot: docroot
services:
  node:
    type: node
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
