_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 35d60ae2-4be1-4d59-bf5a-1d6a56f53498
name: FORTY
mail: feexpert@email.com
slogan: 'BY HTML UP'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
